import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import colors from '../utils/colors'
import { breakpoints as bp } from '../utils/layout'
import Image from 'next/image'
import CityBike1 from '../assets/images/City_Bike1.jpeg'

const Container = styled.div`
  background: ${colors.white};
  height: 100vh;
`

const PageHeadingContainer = styled.div`
  background: ${colors.darkGray};
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 30px 0;
`

const Heading = styled.h1`
  text-shadow: 0.6px 0 0;
  font-size: 20px;

  @media (min-width: ${bp.md}) {
    font-size: 40px;
  }
`
const ImageContainer = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  margin: 40px 10px;
`

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>BIKE FINLAND </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <PageHeadingContainer>
        <Heading>City Bikes</Heading>
      </PageHeadingContainer>
      <ImageContainer>
        <Image src={CityBike1} alt='City Bike' width={900} height={500} />
      </ImageContainer>
    </Container>
  )
}

export default Home
