import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import colors from '../utils/colors'

const Container = styled.div`
  background: ${colors.gray};
  height: 100vh;
`

const PageHeadingContainer = styled.div`
  background: ${colors.darkGray};
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 30px 0;
`

const Heading = styled.h1`
  text-shadow: 0.6px 0 0;
  font-size: 20px;
`

const Home: NextPage = ({ isConnected }: any) => {
  return (
    <Container>
      <Head>
        <title>BIKE FINLAND </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <PageHeadingContainer>
        <Heading>City Bikes</Heading>
      </PageHeadingContainer>
    </Container>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async (context) => {
  return {
    props: { isConnected: true },
  }
}
