import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import colors from '../utils/colors'
import { breakpoints as bp } from '../utils/layout'
import Image from 'next/image'
import CityBike1 from '../assets/images/City_Bike1.jpeg'
import PassCard from '../components/PassCard'
import InstructionCard from '../components/InstructionCard'

const Container = styled.div`
  background: ${colors.white};
  height: 100vh;
`

const PageHeadingContainer = styled.div`
  background: ${colors.darkGray};
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 30px 0;
`

const Heading = styled.h1`
  text-shadow: 0.6px 0 0;
  font-size: 20px;

  @media (min-width: ${bp.md}) {
    font-size: 40px;
  }
`

const HeroContainer = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  margin: 40px 10px;
`

const HeroTextContainer = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`

const HeroHeading = styled.h1`
  font-weight: 400;
  font-size: 16px;
  padding: 20px;

  @media (min-width: ${bp.md}) {
    font-size: 25px;
  }

  @media (min-width: ${bp.lg}) {
    font-size: 35px;
  }
`

const HeroTexts = styled.h1`
  font-weight: 400;
  font-size: 13px;
  padding: 10px;

  @media (min-width: ${bp.md}) {
    font-size: 15px;
    padding: 20px 100px;
  }
  @media (min-width: ${bp.lg}) {
    font-size: 20px;
  }
`
const ImageContainer = styled.div`
  padding: 20px;
`
const BuyPassContainer = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background: ${colors.gray};
  padding-bottom: 50px;
`
const CardsContainer = styled.div`
  display: flex;
  flex-direction: column;
  width: 100%;
  margin-bottom: 20px;

  @media (min-width: ${bp.md}) {
    flex-direction: row;
    margin-bottom: 50px;
  }
`
const InstructionContainer = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding-bottom: 30px;
`

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>BIKE FINLAND </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/City_Bike3.png' />
      </Head>
      <PageHeadingContainer>
        <Heading>City Bikes</Heading>
      </PageHeadingContainer>
      <HeroContainer>
        <HeroTextContainer>
          <HeroHeading>Welcome to Helsinki City Bikes!</HeroHeading>
          <HeroTexts>
            Find the closest available bike and hop on! The bikes are available
            from the beginning of April until the end of October.
          </HeroTexts>
        </HeroTextContainer>
        <ImageContainer>
          <Image src={CityBike1} alt='City Bike' width={900} height={500} />
        </ImageContainer>
      </HeroContainer>
      <BuyPassContainer>
        <HeroHeading>Buy a Pass </HeroHeading>
        <CardsContainer>
          <PassCard />
        </CardsContainer>
      </BuyPassContainer>
      <InstructionContainer>
        <HeroHeading>How it works</HeroHeading>
        <CardsContainer>
          <InstructionCard />
        </CardsContainer>
      </InstructionContainer>
    </Container>
  )
}

export default Home
